title: Silvana Castillo Guerra
description: Geospatial Data Analysis | Climate | Landslides
url: "https://silvanacg.github.io"
baseurl: ""
google_site_verification: <meta name="google-site-verification" content="ZhMnHs5VLrIi2OjWbbWeEyYVWrdyAiZuERUbZm1JGUo" />
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Pick a skin (you can change later)
minimal_mistakes_skin: "air"

# Tell the theme to use a top nav
defaults:
  - scope:
      path: ""
    values:
      layout: single
      
collections:
  projects:
    output: true
    permalink: /projects/:name/
